-- =============================================================================
-- 09_mart__load_dimensions.sql
-- Purpose: Populate mart dimensions (idempotent upserts)
-- =============================================================================

-- Ensure schema exists
CREATE SCHEMA IF NOT EXISTS mart;

-- Ensure dimension tables exists
CREATE TABLE IF NOT EXISTS mart.dim_state (
  state_sk   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state_code CHAR(2) NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_state_state_code ON mart.dim_state (state_code);

CREATE TABLE IF NOT EXISTS mart.dim_month (
  month_sk   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  month_date DATE NOT NULL,
  year       SMALLINT NOT NULL,
  month      SMALLINT NOT NULL,
  ym         TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_month_month_date ON mart.dim_month (month_date);

CREATE TABLE IF NOT EXISTS mart.dim_retail_sector (
  sector_sk   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sector_code TEXT NOT NULL,
  sector_name TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_retail_sector_code ON mart.dim_retail_sector (sector_code);

CREATE TABLE IF NOT EXISTS mart.dim_fuel (
  fuel_sk    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fuel_code  TEXT NOT NULL,
  fuel_name  TEXT NOT NULL,
  fuel_group TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_fuel_code ON mart.dim_fuel (fuel_code);

-- dim_state
WITH states AS (
  SELECT DISTINCT UPPER(TRIM(state_code))::CHAR(2) AS state_code
  FROM stage.retail_state_month_sector
  WHERE NULLIF(TRIM(state_code), '') IS NOT NULL

  UNION
  SELECT DISTINCT UPPER(TRIM(state_code))::CHAR(2)
  FROM stage.ops_state_month_controls
  WHERE NULLIF(TRIM(state_code), '') IS NOT NULL

  UNION
  SELECT DISTINCT UPPER(TRIM(state_code))::CHAR(2)
  FROM stage.dc_state_exposure
  WHERE NULLIF(TRIM(state_code), '') IS NOT NULL

  UNION
  SELECT DISTINCT UPPER(TRIM(state_code))::CHAR(2)
  FROM stage.data_centers_operating
  WHERE NULLIF(TRIM(state_code), '') IS NOT NULL
),
names AS (
  SELECT UPPER(TRIM(stateid))::CHAR(2) AS state_code
  FROM raw.eia_retail_sales
  WHERE TRIM(stateid) ~ '^[A-Za-z]{2}$'
  GROUP BY 1
)
INSERT INTO mart.dim_state (state_code)
SELECT state_code
FROM states
ON CONFLICT (state_code) DO NOTHING;
-- dim_month (generate full month series between observed min/max)
WITH bounds AS (
  SELECT
    DATE_TRUNC('month', MIN(month_date))::DATE AS min_m,
    DATE_TRUNC('month', MAX(month_date))::DATE AS max_m
  FROM (
    SELECT month_date FROM stage.retail_state_month_sector
    UNION ALL
    SELECT month_date FROM stage.ops_state_month_controls
  ) x
),
months AS (
  SELECT generate_series(min_m, max_m, interval '1 month')::DATE AS month_date
  FROM bounds
  WHERE min_m IS NOT NULL AND max_m IS NOT NULL
)
INSERT INTO mart.dim_month (month_date, year, month, ym)
SELECT
  month_date,
  EXTRACT(YEAR FROM month_date)::SMALLINT  AS year,
  EXTRACT(MONTH FROM month_date)::SMALLINT AS month,
  TO_CHAR(month_date, 'YYYY-MM')           AS ym
FROM months
ON CONFLICT (month_date) DO UPDATE
SET
  year  = EXCLUDED.year,
  month = EXCLUDED.month,
  ym    = EXCLUDED.ym;

-- dim_retail_sector
WITH sectors AS (
  SELECT DISTINCT UPPER(TRIM(sector_code)) AS sector_code
  FROM stage.retail_state_month_sector
  WHERE NULLIF(TRIM(sector_code), '') IS NOT NULL
),
names AS (
  SELECT
    UPPER(TRIM(sectorid)) AS sector_code,
    MAX(sectorname)       AS sector_name
  FROM raw.eia_retail_sales
  WHERE NULLIF(TRIM(sectorid), '') IS NOT NULL
  GROUP BY 1
)
INSERT INTO mart.dim_retail_sector (sector_code, sector_name)
SELECT
  s.sector_code,
  COALESCE(
    n.sector_name,
    CASE s.sector_code
      WHEN 'RES' THEN 'Residential'
      WHEN 'COM' THEN 'Commercial'
      WHEN 'IND' THEN 'Industrial'
      WHEN 'TRA' THEN 'Transportation'
      WHEN 'OTH' THEN 'Other'
      ELSE NULL
    END
  ) AS sector_name
FROM sectors s
LEFT JOIN names n USING (sector_code)
ON CONFLICT (sector_code) DO UPDATE
SET sector_name = COALESCE(EXCLUDED.sector_name, mart.dim_retail_sector.sector_name);

-- dim_fuel (small, analysis-friendly set)
INSERT INTO mart.dim_fuel (fuel_code, fuel_name, fuel_group)
VALUES
  ('TOTAL',   'Total generation',   'total'),
  ('COAL',    'Coal generation',    'coal'),
  ('GAS',     'Natural gas generation', 'gas'),
  ('NUCLEAR', 'Nuclear generation', 'nuclear'),
  ('RENEW',   'Renewable generation','renew')
ON CONFLICT (fuel_code) DO UPDATE
SET
  fuel_name  = EXCLUDED.fuel_name,
  fuel_group = EXCLUDED.fuel_group;

